DROP TABLE IF EXISTS HASPROTEINS CASCADE;
DROP TABLE IF EXISTS UNIPROT CASCADE;
DROP TABLE IF EXISTS SECONDARYSTRUCTURE CASCADE;
DROP TABLE IF EXISTS CRYSTALSTRUCTURESEQUENCE CASCADE;
DROP TABLE IF EXISTS CRYSTALSTRUCTURE CASCADE;
DROP TABLE IF EXISTS GOPROCESSES CASCADE;
DROP TABLE IF EXISTS GOFUNCTIONS CASCADE;
DROP TABLE IF EXISTS REFSEQ CASCADE;


CREATE TABLE UNIPROT (
	UNIPROT_ID VARCHAR(3000),
	FULLNAME VARCHAR(3000),
	PROTEINNAME VARCHAR(3000),
	GENENAME VARCHAR(3000),
	MASS NUMERIC,
	PROTEINLENGTH NUMERIC,
	PROTEINSEQUENCE VARCHAR(40000),
	PRIMARY KEY (UNIPROT_ID));

CREATE TABLE SECONDARYSTRUCTURE (
	PROTEINLENGTH NUMERIC,
	PDB_ID VARCHAR(30),
	PROTEINSEQUENCE VARCHAR(40000),
	SST8 VARCHAR(40000),
	SST3 VARCHAR(40000),
	CHAINCODE VARCHAR(30),
	PRIMARY KEY (PDB_ID, CHAINCODE));

CREATE TABLE CRYSTALSTRUCTURESEQUENCE (
	PDB_ID VARCHAR(30),
	CHAINID VARCHAR(30),
	PROTEINSEQUENCE VARCHAR(40000),
	RESIDUECOUNT VARCHAR(30),
	MACROMOLECULETYPE VARCHAR(300),
	PRIMARY KEY (PDB_ID, CHAINID));

CREATE TABLE CRYSTALSTRUCTURE (
	PDB_ID VARCHAR(300),
	CLASSIFICATION VARCHAR(300),
	EXPERIMENTTECHNIQUE VARCHAR(300),
	MACROMOLECULETYPE VARCHAR(300),
	RESIDUECOUNT INT,
	RESOLUTION NUMERIC(300),
	STRUCTUREMOLECULARWEIGHT NUMERIC(300),
	CRYSTALIZATIONMETHOD VARCHAR(300),
	CRYSTALIZATIONTEMPK NUMERIC(300),
	DENSITYMATHEWS NUMERIC(300),
	DENSITYPERCENTSOL NUMERIC NULL,
	PDBXDETAILS VARCHAR(3000),
	PHVALUE NUMERIC(30) NULL,
	PUBLICATIONYEAR INT,
	PRIMARY KEY (PDB_ID));

CREATE TABLE REFSEQ (
	UNIPROT_ID VARCHAR(3000),
	REFSEQ VARCHAR(3000),
	FOREIGN KEY (UNIPROT_ID) REFERENCES UNIPROT(UNIPROT_ID),
	PRIMARY KEY (UNIPROT_ID, REFSEQ));

CREATE TABLE GOPROCESSES (
	UNIPROT_ID VARCHAR(3000),
	CELLPROCESSID VARCHAR(3000),
	CELLPROCESS VARCHAR(3000),
	FOREIGN KEY (UNIPROT_ID) REFERENCES UNIPROT(UNIPROT_ID),
	PRIMARY KEY (UNIPROT_ID, CELLPROCESSID));
	
CREATE TABLE GOFUNCTIONS (
	UNIPROT_ID VARCHAR(3000),
	GOFUNCTIONID VARCHAR(3000),
	GOFUNCTION VARCHAR(3000),
	FOREIGN KEY (UNIPROT_ID) REFERENCES UNIPROT(UNIPROT_ID),
	PRIMARY KEY (UNIPROT_ID, GOFUNCTIONID));

CREATE TABLE HASPROTEINS (
	UNIPROT_ID VARCHAR(30),
	PDB_ID VARCHAR(30),
	FOREIGN KEY(UNIPROT_ID) REFERENCES UNIPROT(UNIPROT_ID),
	--FOREIGN KEY(PDB_ID) REFERENCES CRYSTALSTRUCTURE(PDB_ID),
	PRIMARY KEY (PDB_ID, UNIPROT_ID));

COPY crystalstructuresequence FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/crystalstructuresequence_COMP533.csv' WITH (FORMAT csv);
COPY crystalstructure FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/structure.csv' WITH (FORMAT csv);
COPY secondarystructure FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/secondarystructure_COMP533.csv' WITH (FORMAT csv);
COPY uniprot FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/uniprot_2.csv' WITH (FORMAT csv);
COPY hasproteins FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/hasproteins_COMP533.csv' WITH (FORMAT csv);
COPY refseq FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/refseqTable.csv' WITH (FORMAT csv);
COPY goprocesses FROM '/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/processTable.csv' WITH (FORMAT csv);

COPY gofunctions FROM 
'/Users/da39/Desktop/CLASS_WORK/building_a_database/curated_csvs/functionTable.csv' 
WITH (FORMAT csv);





