name: debext-cdci-actions
on: [push]
jobs:
  basic-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: DebruijnExtend_environment.yaml
          activate-environment: DebruinExtend
          auto-activate-base: false
      - name: activate env
        run: conda activate DebruinExtend;
      - name: run unit tests
        run: python -m unittest src/tests/test_DebruijnExtend.py  
