name: debext-cdci-actions
on: [push]

jobs:
  basic-testing:
    runs-on: "macos-latest"
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest"]
    steps:
      - name: Build Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: DebruijnExtend_environment.yaml
          activate-environment: DebruinExtend
          auto-activate-base: false
      - uses: conda-incubator/setup-miniconda@v2
        shell: bash -l {0}
        with:
          activate-environment: DebruijnExtend
      - name: run unit tests
        shell: bash -l {0}
        run: python3 -m unittest src/tests/test_DebruijnExtend.py  
