name: debext-cdci-actions
on: [push]
jobs:
  basic-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: set up conda env
        uses: conda-incubator/setup-miniconda@v2
          with:
            miniconda-version: "latest"
      - name: activate env
        run: conda env create -f DebruijnExtend_environment.yaml
      - name: run unit tests
        run: python -m unittest src/tests/test_DebruijnExtend.py  
